CREATE TABLE t_student
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    surname       VARCHAR(255),
    name          VARCHAR(255),
    patronymic    VARCHAR(255),
    university_id BIGINT,
    card_id       BIGINT,
    CONSTRAINT pk_t_student PRIMARY KEY (id)
);

CREATE TABLE t_student_card
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number     VARCHAR(255),
    direction  INTEGER,
    student_id BIGINT,
    CONSTRAINT pk_t_student_card PRIMARY KEY (id)
);

CREATE TABLE t_teacher
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    surname       VARCHAR(255),
    name          VARCHAR(255),
    patronymic    VARCHAR(255),
    university_id BIGINT,
    CONSTRAINT pk_t_teacher PRIMARY KEY (id)
);

CREATE TABLE t_university
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_t_university PRIMARY KEY (id)
);

CREATE TABLE teacher_student
(
    student_id BIGINT NOT NULL,
    teacher_id BIGINT NOT NULL,
    CONSTRAINT pk_teacher_student PRIMARY KEY (student_id, teacher_id)
);

ALTER TABLE t_student_card
    ADD CONSTRAINT FK_T_STUDENT_CARD_ON_STUDENT FOREIGN KEY (student_id) REFERENCES t_student (id);

ALTER TABLE t_student
    ADD CONSTRAINT FK_T_STUDENT_ON_CARD FOREIGN KEY (card_id) REFERENCES t_student_card (id);

ALTER TABLE t_student
    ADD CONSTRAINT FK_T_STUDENT_ON_UNIVERSITY FOREIGN KEY (university_id) REFERENCES t_university (id);

ALTER TABLE t_teacher
    ADD CONSTRAINT FK_T_TEACHER_ON_UNIVERSITY FOREIGN KEY (university_id) REFERENCES t_university (id);

ALTER TABLE teacher_student
    ADD CONSTRAINT fk_teastu_on_student FOREIGN KEY (student_id) REFERENCES t_student (id);

ALTER TABLE teacher_student
    ADD CONSTRAINT fk_teastu_on_teacher FOREIGN KEY (teacher_id) REFERENCES t_teacher (id);